
## DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/auction
spring.datasource.username=postgres
spring.datasource.password=123

##JPA
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

##JWT
jwt.secret = 4230423592359fgdg92304123-90gdf09gxc09ui2093uc09df
jwt.lifetime = 30M