
## DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/auction
spring.datasource.username=postgres
spring.datasource.password=123

##JPA
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true